name: build

on: 
  workflow_call:
    secrets:
      DOCKER_TOKEN:
        required: true
  workflow_dispatch:

env:
  DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs: 
    main:
        runs-on: ubuntu-22.04-arm
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: build docker image
              run: | 
                echo "$DOCKER_TOKEN" | docker login -u charan1924 --password-stdin
                # docker buildx create --use --name multiarch-builder
                # docker buildx build --platform linux/arm64 -t charan1924/crud-app:arm-latest --load .
                docker build -t charan1924/crud-app-arm:${{ github.sha }} .

            - name: push image to docker hub
              run: |
                  # echo "$DOCKER_TOKEN" | docker login -u charan1924 --password-stdin
                  docker push charan1924/crud-app-arm:${{ github.sha }}

    update-manifest:
        needs: main
        runs-on: ubuntu-22.04
        steps:
          - name: checkout manifest repo
            uses: actions/checkout@v4
            with: 
              repository: 'Charan-Sharan/gitops'
              path: ./gitops
              ref: main
              token: ${{ secrets.GITOPS }}

          - name: update tag
            run : | 
              sed 's/image:*/image: crud-app-arm:${{ github.sha }}/g' -i gitops/deployment.yml

          - name: push changes
            env: 
              GH_TOKEN: ${{ secrets.GITOPS }}
            working-directory: ./gitops
            run: |
              git config --global user.email  "charansharan2004+github@gmail.com"
              git config --global user.name "charansharan"
              git add .
              git commit -m "Update deployment manifest crud-app-arm:${{ github.sha }}"
              git push https://x-access-token:${GH_TOKEN}@github.com/Charan-Sharan/gitops.git 
