name: test

on: 
    push:
        branches:
            - main

jobs: 
    run-tests: 
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: run tests
              run: |
                echo "Running tests........"
                echo "[ PASS ] test-1"
                echo "[ PASS ] test-2"
                echo "[ PASS ] test-3"
                echo "[ PASS ] test-4"
                echo "All tests passed"
    build:
        needs: run-tests
        uses: .github/workflows/build-and-publish.yml